#!/bin/bash
# copies file from head instances

source ec2-config

# if not enough arguments print usage
if [ "$#" -lt 2 ]; then
    echo "Usage:  $(basename $0) FileOnHeadNode  LocalCopy"
    echo "  example: $(basename $0) /file/on/head/node /target/path/on/local/machine"
    exit
fi

scp -i ${SWIFT_EC2_KEY} $SWIFT_EC2_USER@$(sed -n "1,1p" head_node_public_ip.txt | cat):$1 $2 # copy file



