#!/bin/bash
# removes file on head ec2 instance

source ec2-config

# if not enough arguments print usage
if [ "$#" -lt 1 ]; then
    echo "Usage:  $(basename $0) instance_file"
    echo "  example: $(basename $0) /file/to/delete "
    exit
fi

ssh -i ${SWIFT_EC2_KEY}  $SWIFT_EC2_USER@$(sed -n "1,1p" head_node_public_ip.txt | cat) "source ~/.bash_profile; rm $1"


