#!/bin/bash
# removes file on all ec2 instances

source ec2-config

# if not enough arguments print usage
if [ "$#" -lt 1 ]; then
    echo "Usage:  $(basename $0) instance_file"
    echo "  example: $(basename $0) /file/to/delete "
    exit
fi


# store public ips in an array
iparr=($(cat public_ip.txt | awk '{ print $1 }'))

for i in "${iparr[@]}"
do
	ssh -i ${SWIFT_EC2_KEY}  $SWIFT_EC2_USER@${i} 'source ~/.profile; rm' $1
done

