#!/bin/bash
# copies file from all instances to CopyDirectory 

source swift-t_ec2_config

# if not enough arguments print usage
if [ "$#" -lt 2 ]; then
    echo "Usage:  $(basename $0) FilePathOnInstance CopyDirectory"
    echo "  example: $(basename $0) /file/on/instance /directory/on/local/machine"
    exit
fi


# store public ips in an array
iparr=($(cat public_ip.txt | awk '{ print $1 }'))

for i in "${iparr[@]}"
do
	scp -i ${SWIFT_EC2_KEY} $SWIFT_EC2_USER@${i}:$1 $2/${i}-$(basename $1) # copy file
done

